[build-system]
requires = [
    "setuptools>=54",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "Core"
version = "0.1.6"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "transformers",
]
